# Default values for fabricx
global:
  registry: fabricx

authService:
  enabled: true
  replicaCount: 3
  image:
    repository: fabricx/auth
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

agentState:
  enabled: true
  replicaCount: 2
  image:
    repository: fabricx/agent-state
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

interactionService:
  enabled: true
  replicaCount: 2
  image:
    repository: fabricx/interaction-service
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
    targetPort: 8082
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}